### ISSUE TITLE
Click exception in manage.py

### ISSUE THREAD

**Issue by stefreak** [arugifa/europython-2018-workshop#9]
```(venv) sneubauer:ep2018-workshop sneubauer$ ./manage.py demo
Traceback (most recent call last):
  File "./manage.py", line 33, in <module>
    'db_url', envvar=DATABASE_URL, help="How to connect to the database.")
  File "/Users/sneubauer/work/github/ep2018-workshop/venv/lib/python3.6/site-packages/click/decorators.py", line 151, in decorator
    _param_memo(f, ArgumentClass(param_decls, **attrs))
  File "/Users/sneubauer/work/github/ep2018-workshop/venv/lib/python3.6/site-packages/click/core.py", line 1699, in __init__
    Parameter.__init__(self, param_decls, required=required, **attrs)
TypeError: __init__() got an unexpected keyword argument 'help'```

**Comment by stefreak** [comment]
fixed
